#!/usr/bin/env python3
"""Generate english/wordnet.pl from a WordNet 3.1 dict/ directory.

    python3 tools/gen_wordnet.py DICT_DIR OUT_FILE

The grammar checker's own lexicon, english/lexicon.pl, lists a few hundred
words by hand. This turns WordNet's much larger one into Prolog facts that
the checker can load beside it (english/wordnet_check.pl), for stage 3 of the
grammar in docs/ROADMAP.md. `make wordnet` downloads WordNet and runs this;
the output is not committed, as it is generated, large, and WordNet's.

What is kept: single words of lowercase letters, from the four index files,
and the irregular forms in noun.exc and verb.exc. What each verb takes after
it is read from the sentence frames WordNet gives every verb sense, mapped to
the grammar's three frames:

    intrans   nothing, or only a prepositional phrase   "Somebody ----s"
    trans     one noun phrase, perhaps with a PP        "Somebody ----s something"
    ditrans   two noun phrases                          "Somebody ----s somebody something"

Frames that take a clause, an infinitive, an -ing form or an adjective have
no counterpart in the grammar yet and are left out.
"""

import os
import re
import sys

WORD = re.compile(r'^[a-z]{2,}$')

# WordNet's 35 verb frames (dict/verb.Framestext), by the grammar frame each
# one means; a frame absent from both sets is not used.
INTRANS = {1, 2, 3, 4, 12, 13, 22, 23, 27}
TRANS = {5, 8, 9, 10, 11, 15, 16, 17, 18, 19, 20, 21, 24, 25, 30, 31}
DITRANS = {14}


def lemmas(path):
    """The lemmas of an index file, skipping its license header."""
    out = []
    with open(path, encoding='utf-8') as f:
        for line in f:
            if line.startswith('  '):
                continue
            lemma = line.split(' ', 1)[0]
            if WORD.match(lemma):
                out.append(lemma)
    return out


def verb_frames(path):
    """For each verb, the grammar frames of all its senses."""
    frames = {}
    with open(path, encoding='utf-8') as f:
        for line in f:
            if line.startswith('  '):
                continue
            fields = line.split(' | ', 1)[0].split()
            # synset_offset lex_filenum ss_type w_cnt word lex_id [word lex_id...]
            w_cnt = int(fields[3], 16)
            words = [fields[4 + 2 * i].lower() for i in range(w_cnt)]
            i = 4 + 2 * w_cnt
            p_cnt = int(fields[i])
            i += 1 + 4 * p_cnt
            if i >= len(fields):
                continue
            f_cnt = int(fields[i])
            i += 1
            for _ in range(f_cnt):
                # + f_num w_num: w_num 00 means every word of the synset
                f_num, w_num = int(fields[i + 1]), int(fields[i + 2], 16)
                i += 3
                targets = words if w_num == 0 else [words[w_num - 1]]
                for w in targets:
                    if not WORD.match(w):
                        continue
                    s = frames.setdefault(w, set())
                    if f_num in INTRANS:
                        s.add('intrans')
                    elif f_num in TRANS:
                        s.add('trans')
                    elif f_num in DITRANS:
                        s.add('ditrans')
    return frames


def exceptions(path):
    """(form, base) pairs from an exception list, single words only."""
    out = []
    with open(path, encoding='utf-8') as f:
        for line in f:
            parts = line.split()
            if len(parts) >= 2 and WORD.match(parts[0]) and WORD.match(parts[1]):
                out.append((parts[0], parts[1]))
    return out


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    d, out = sys.argv[1], sys.argv[2]
    nouns = lemmas(os.path.join(d, 'index.noun'))
    verbs = lemmas(os.path.join(d, 'index.verb'))
    adjs = lemmas(os.path.join(d, 'index.adj'))
    advs = lemmas(os.path.join(d, 'index.adv'))
    frames = verb_frames(os.path.join(d, 'data.verb'))
    order = ['intrans', 'trans', 'ditrans']
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/*  english/wordnet.pl -- generated by tools/gen_wordnet.py from\n'
                '    WordNet 3.1; do not edit. `make wordnet` rebuilds it.\n\n'
                '    WordNet 3.1 Copyright 2011 by Princeton University. All rights\n'
                '    reserved. WordNet is used under its license, which is at\n'
                '    https://wordnet.princeton.edu/license-and-commercial-use and in\n'
                '    the header of every file of its database.\n*/\n\n')
        for w in nouns:
            f.write("wn_noun('%s').\n" % w)
        for w in verbs:
            fs = [x for x in order if x in frames.get(w, ())]
            if fs:
                f.write("wn_verb('%s', [%s]).\n" % (w, ', '.join(fs)))
        for w in adjs:
            f.write("wn_adj('%s').\n" % w)
        for w in advs:
            f.write("wn_adv('%s').\n" % w)
        for form, base in exceptions(os.path.join(d, 'noun.exc')):
            f.write("wn_irregular(noun, '%s', '%s').\n" % (form, base))
        for form, base in exceptions(os.path.join(d, 'verb.exc')):
            f.write("wn_irregular(verb, '%s', '%s').\n" % (form, base))


if __name__ == '__main__':
    main()
